# Generated by Django 4.0.5 on 2022-06-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0002_alter_comments_issue_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='tittle',
            new_name='title',
        ),
    ]
