# Generated by Django 4.0.5 on 2022-06-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0003_rename_tittle_issues_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
