# Generated by Django 4.0.5 on 2022-06-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0004_users_email_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
