# Generated by Django 4.0.5 on 2022-06-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0006_rename_issue_id_comments_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue',
            new_name='issue_id',
        ),
    ]
