# Generated by Django 4.0.5 on 2022-06-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDesk', '0007_rename_issue_comments_issue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue_id',
            new_name='issues_id',
        ),
    ]
